source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

# ignore all warnings from all pods
inhibit_all_warnings!

use_frameworks!


def pods
	pod 'MJExtension'
	pod 'MJRefresh'
    pod 'SDWebImage'
    pod 'AFNetworking', '~> 3.0'
    pod 'FSPagerView'
    pod 'MBProgressHUD'
    pod 'HUPhotoBrowser'
end

target 'MyPhoto' do
    pods
end

