source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

# ignore all warnings from all pods
inhibit_all_warnings!

use_frameworks!


def pods
	pod 'MJExtension'
	pod 'MJRefresh'
	pod 'SDWebImage', '~> 4.0'
	pod 'AFNetworking', '~> 3.0'
    pod 'FSPagerView'

end

target 'MyPhoto' do
    pods
end

